module.exports.groupTitle = [
  { title: "수학 열정", subject: "수학" },
  { title: "과학 탐구", subject: "과학" },
  { title: "영어 독해", subject: "영어" },
  { title: "역사의 흐름", subject: "역사" },
  { title: "사회 문제 해결", subject: "사회" },
  { title: "문학 산책", subject: "문학" },
  { title: "미술 감상", subject: "미술" },
  { title: "음악 이론", subject: "음악" },
  { title: "체육 실력 향상", subject: "체육" },
  { title: "정치와 경제", subject: "정치, 경제" },
  { title: "심리학 탐구", subject: "심리학" },
  { title: "컴퓨터 프로그래밍", subject: "컴퓨터 과학" },
  { title: "비즈니스 전략", subject: "경영학" },
  { title: "법과 사회", subject: "법학, 사회학" },
  { title: "언어와 문화", subject: "언어학, 문화학" },
  { title: "환경 과학", subject: "환경 과학" },
  { title: "인류학 탐구", subject: "인류학" },
  { title: "철학적 사고", subject: "철학" },
  { title: "지리적 탐색", subject: "지리학" },
  { title: "국제 관계", subject: "국제 관계" },
  { title: "영상 제작", subject: "영상 제작" },
  { title: "수리 논리학", subject: "수리 논리학" },
  { title: "생명 과학", subject: "생명 과학" },
  { title: "언론과 커뮤니케이션", subject: "언론, 커뮤니케이션" },
  { title: "의학 윤리", subject: "의학 윤리" },
  { title: "국어 작문", subject: "국어" },
  { title: "실용 외국어", subject: "외국어" },
  { title: "경영 전략", subject: "경영학" },
  { title: "문화 사회학", subject: "문화 사회학" },
  { title: "물리 실험", subject: "물리학" },
  { title: "정치 이론", subject: "정치학" },
  { title: "심리 검사", subject: "심리학" },
  { title: "디자인 원리", subject: "디자인" },
  { title: "지구 과학", subject: "지구 과학" },
  { title: "인문학 연구", subject: "인문학" },
  { title: "음악 감상", subject: "음악" },
  { title: "통계 분석", subject: "통계학" },
  { title: "화학 실험", subject: "화학" },
  { title: "도시 계획", subject: "도시 계획" },
  { title: "사회 심리학", subject: "사회 심리학" },
  { title: "미디어와 사회", subject: "미디어, 사회학" },
  { title: "영화 감상", subject: "영화" },
  { title: "수학 모델링", subject: "수학" },
  { title: "공학 개론", subject: "공학" },
  { title: "정치 경제학", subject: "정치학, 경제학" },
  { title: "문화 인류학", subject: "문화 인류학" },
  { title: "물리 이론", subject: "물리학" },
  { title: "음악 이론", subject: "음악" },
  { title: "사회조사 방법론", subject: "사회학" },
  { title: "환경 윤리", subject: "환경 윤리" },
];
